### PR TITLE
Update live.py

### PR DESCRIPTION
**Pull request by k-prabin**
fix

### CODE REVIEW

**Comment by divyankm** [comment]
Pls update this line as well.
1. [history.py#L41](https://github.com/k-prabin/jugaad-data/blob/patch-1/jugaad_data/nse/history.py#L41)
2. [archives.py#L150](https://github.com/k-prabin/jugaad-data/blob/patch-1/jugaad_data/nse/archives.py#L150)

**Comment by skyler-guha** [comment]
This seems to work. Thanks!!
(only tested it on historical data tho)

Incase anyone wants to install the forked repo with the patches:
pip install https://github.com/k-prabin/jugaad-data/archive/refs/heads/patch-1.zip

**Comment by k-prabin** [comment]
> Pls update this line as well.
> 
> 1. [history.py#L41](https://github.com/k-prabin/jugaad-data/blob/patch-1/jugaad_data/nse/history.py#L41)
> 2. [archives.py#L150](https://github.com/k-prabin/jugaad-data/blob/patch-1/jugaad_data/nse/archives.py#L150)

done

**Comment by k-prabin** [comment]
working?

**Comment by buzzvolt** [comment]
please check use of brotli when dealing with br responses and see if requests could use that -- I have pr#88

**Comment by buzzvolt** [comment]
guys try out https://github.com/jugaad-py/jugaad-data/pull/88 if that solves your problem

**Comment by sevakram** [comment]
Thanks for the contribution, Sorry, I saw this late, I am combining this with other changes in my PR.

**Pull request closed without merging**
